media:
  input: src/media
  output: /media

content:

  - name: celebrities
    label: Celebrities
    type: collection
    folder: json/celebrity
    create: true
    fields:
      - { name: first_name, label: First Name, type: string }
      - { name: last_name, label: Last Name, type: string }
      - { name: id, label: ID, type: string }
      - { name: image, label: Image, type: string }

  - name: history
    label: History
    type: collection
    folder: json/history
    create: true
    fields:
      - { name: first_name, label: First Name, type: string }
      - { name: last_name, label: Last Name, type: string }
      - { name: id, label: ID, type: string }
      - { name: image, label: Image, type: string }

  - name: tv
    label: TV Shows
    type: collection
    folder: json/tv
    create: true
    fields:
      - { name: first_name, label: First Name, type: string }
      - { name: last_name, label: Last Name, type: string }
      - { name: id, label: ID, type: string }
      - { name: image, label: Image, type: string }

  - name: videogames
    label: Video Games
    type: collection
    folder: json/videogames
    create: true
    fields:
      - { name: first_name, label: First Name, type: string }
      - { name: last_name, label: Last Name, type: string }
      - { name: id, label: ID, type: string }
      - { name: image, label: Image, type: string }

actions:
  - name: deploy-site
    label: Deploy site
    workflow: pages-cms-action.yml